LicenceKey: <Your Licence Key>
# Select desired exchange platform to trade, { BinancePerpetual | BybitUsdtPerpetual }
platform: BinancePerpetual
publicKey: <Public Api Key>
secretKey: <Secret Api Key>
# Specify which symbol you want to trade
symbol: BTCUSDT
# Waiting time in seconds between each trading loop
interval: 10

openPosition:
  # Choose a side to trade, { Buy | Sell }
  tradingSide: Sell
  # Enable or Disable auto open position, { true | false }
  autoOpenPosition: true
  # How long the bot should wait between closing a position and opening a new one, { integer }
  coolDownInSeconds: 10

managePosition:
  # Indicates the size of each market maker order, { float }
  scaleOrderSizeValue: 0.01
  # Indicates the maximum size of a position can hold, { float }
  maxContractSize: 1

  protection:
    # Buy Protection setting is used for both double buy and half buy protection
    # Enable or Disable buy protection, {true | false }
    useBuyProtection: true
    # Indicates the percentage to kick double buy protection in, { float }
    buyProtectionPercentage: 0.02

    # Indicates the size when the bot will wait for the price to away from entry to continue trading
    noTradingZoneSize: 1
    # Indicates when the bot will start trading after price moving away from entry price by this much
    noTradingZoneRange: 1

closePosition:
  # Choose a type of tp to use, { Limit | Trailing }
  typeOfTp: Trailing

  limitTpPercentage: 0.001

  # If typeOfTp is trailing, these settings will be used, otherwise
  # they have no affect on limit tp process.

  # Indicates when the bot will start trailing, { float }
  trailingStart: 0.0005
  # Indicates how far behind it will trail tp order to be placed, { float }
  trailingPercentage: 0.0005



lossPosition:
  # Enable or Disable stop loss functionality, { true | false }
  useStopLoss: true

  # Indicates...
  stopLossPercentage: 0.01
